### ISSUE TITLE
App Crashes non-stop and is hard to debug

### ISSUE THREAD

**Issue by grobbo91** [kaismic/Custom-Layout-Keyboard-for-Android#1]
Hi,

I have experimented with a few different custom keyboard examples. Most have an onscreen app which can be launched. This is easier to debug in my view (well this is what I am used to).

I am finding that this keyboard crashes repetitively as soon as it is selected from the "Choose Input Method" dialog. The error message provided in a popup is "Custom Layout Keyboard Keeps Stopping", with options to view app info or to Close the app.

I am getting this error on an API Level 30 Pixel 5 simulator. I am getting the same type of error on an actual hardware running API Level 25 (I adjusted the Android Manifest to allow it to build to this phone) but unfortunately I cannot get the same popup to say the app "Keeps Stopping".

Can this issue please address:
1) providing a guide to install, run and debug the keyboard from Android Studio
2) Investigate what may cause the app to "Keep Stopping" in the first place.

Addressing 1) first may further enable me to solve 2).

**Comment by grobbo91** [comment]
Apologies, had to dust off my debugging skills, I forgot Logcat can provide some assistance without even using the debugger.

I got:

java.lang.RuntimeException: Unable to create service com.soobakjonmat.customlayoutkeyboard.MainKeyboardService: java.lang.NullPointerException: null cannot be cast to non-null type android.os.VibratorManager
at com.soobakjonmat.customlayoutkeyboard.MainKeyboardService.onCreate(MainKeyboardService.kt:113)

Is vibration a new feature not fully released yet?

**Comment by kaismic** [comment]
Hello

First of all, I wanna say that I'm surprised (in a good way) that someone actually had a look at my repo and tried using my app. This is the first time that I saw someone visibly show interest on my app so thanks for that.

Secondly, I'm currently attending university and this app was developed during school holidays as a personal hobby and for personal usage. So I don't really maintain this app unless I have spare time and have nothing else to do.

Anyway, to answer your questions:
1. I don't really have a guide to install, I just built the app and ran it on Android Studio and compiled it on my phone in developer mode so I don't really have an advice for that.
2. I too get "Keep Stopping" messages sometimes while using the app but it actually doesn't cause any major problems which affect my app usage. So I just ignore it since it's not a problem for me.

So I think you will have to debug the error by yourself because I'm currently busy with university stuff. But I'm happy to accept your pull requests if you can debug the errors or you can just fork my project and debug it there.

Sorry I couldn't help you more but I hope this clears thing up.

**Comment by grobbo91** [comment]
Thanks, I started a similar project myself and also have full time work get in the way quite often but I have had a chance to revisit this topic recently.

For me the "Keep Stopping" errors actually prevent the keyboard from displaying all together. It is a very generic message. 

As it turns out, some bugs are becoming more visible simply because I am relearning how to use Android Studio. Many bugs are in regards to using to low level APIs. I will maybe just maintain my own code for a while and see how it goes, I have some cool ideas for future improvements, I will note those down and keep plugging away at them for now. 

Good luck with your studies.
